### ISSUE TITLE
Make error rate configurable

### ISSUE THREAD

**Issue by stbrody** [joyghosh/bloomfilter.js#2]
Currently the false positive rate is a [fixed constant](https://github.com/joyghosh/bloomfilter.js/blob/69db4a1ed7386d1d0321b11568480b44adfd83e8/lib/bloomfilter.js#L13).  It would be nice if this was an argument to the constructor so you could trade off the size of the bloom filter against its false positive rate

**Comment by joyghosh** [comment]
Added configurable error tolerance rate. closing this issue.
